################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_cortex.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma_ex.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_exti.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ex.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gpio.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gtzc.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_hash.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_hash_ex.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr_ex.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc_ex.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rng.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rng_ex.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc_ex.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart_ex.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_rcc.c 

OBJS += \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_cortex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_exti.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gpio.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gtzc.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_hash.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_hash_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rng.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rng_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rtc.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rtc_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart_ex.o \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_ll_rcc.o 

C_DEPS += \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_cortex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_exti.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gpio.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gtzc.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_hash.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_hash_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rng.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rng_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rtc.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rtc_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart_ex.d \
./Drivers/STM32L5xx_HAL_Driver/stm32l5xx_ll_rcc.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_cortex.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_cortex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma_ex.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_dma_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_dma_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_exti.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_exti.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ex.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_flash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gpio.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gtzc.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_gtzc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_gtzc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_hash.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_hash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_hash.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_hash_ex.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_hash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_hash_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr_ex.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc_ex.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rng.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rng.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rng.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rng_ex.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rng_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rng_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rtc.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rtc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rtc_ex.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_rtc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_rtc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart_ex.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_hal_uart_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_hal_uart_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32L5xx_HAL_Driver/stm32l5xx_ll_rcc.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Drivers/STM32L5xx_HAL_Driver/Src/stm32l5xx_ll_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Drivers/STM32L5xx_HAL_Driver/stm32l5xx_ll_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

