################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/bl2_nv_services.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/jumper.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/low_level_com.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/low_level_flash.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/low_level_rng.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/main.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/mpu_armv8m_drv.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/sha256_alt.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/stm32l5xx_hal_msp.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/system_stm32l5xx.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/tfm_bl2_shared_data.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/tfm_low_level_security.c 

OBJS += \
./Application/User/bl2_nv_services.o \
./Application/User/jumper.o \
./Application/User/low_level_com.o \
./Application/User/low_level_flash.o \
./Application/User/low_level_rng.o \
./Application/User/main.o \
./Application/User/mpu_armv8m_drv.o \
./Application/User/sha256_alt.o \
./Application/User/stm32l5xx_hal_msp.o \
./Application/User/system_stm32l5xx.o \
./Application/User/tfm_bl2_shared_data.o \
./Application/User/tfm_low_level_security.o 

C_DEPS += \
./Application/User/bl2_nv_services.d \
./Application/User/jumper.d \
./Application/User/low_level_com.d \
./Application/User/low_level_flash.d \
./Application/User/low_level_rng.d \
./Application/User/main.d \
./Application/User/mpu_armv8m_drv.d \
./Application/User/sha256_alt.d \
./Application/User/stm32l5xx_hal_msp.d \
./Application/User/system_stm32l5xx.d \
./Application/User/tfm_bl2_shared_data.d \
./Application/User/tfm_low_level_security.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/bl2_nv_services.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/bl2_nv_services.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/bl2_nv_services.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/jumper.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/jumper.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/jumper.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/low_level_com.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/low_level_com.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/low_level_com.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/low_level_flash.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/low_level_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/low_level_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/low_level_rng.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/low_level_rng.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/low_level_rng.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/main.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/mpu_armv8m_drv.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/mpu_armv8m_drv.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/mpu_armv8m_drv.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/sha256_alt.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/sha256_alt.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/sha256_alt.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32l5xx_hal_msp.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/stm32l5xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/stm32l5xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/system_stm32l5xx.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/system_stm32l5xx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/system_stm32l5xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/tfm_bl2_shared_data.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/tfm_bl2_shared_data.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/tfm_bl2_shared_data.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/tfm_low_level_security.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Projects/TFM/TFM_SBSFU_Boot/Src/tfm_low_level_security.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Application/User/tfm_low_level_security.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

