################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bl2_main.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/src/boot_record.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/src/bootutil_misc.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/flash_map.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/src/image_rsa.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/src/image_validate.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/keys.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/src/loader.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/src/security_cnt.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/platform/ext/common/uart_stdout.c 

OBJS += \
./Middlewares/trustedfirmware/bl2_main.o \
./Middlewares/trustedfirmware/boot_record.o \
./Middlewares/trustedfirmware/bootutil_misc.o \
./Middlewares/trustedfirmware/flash_map.o \
./Middlewares/trustedfirmware/image_rsa.o \
./Middlewares/trustedfirmware/image_validate.o \
./Middlewares/trustedfirmware/keys.o \
./Middlewares/trustedfirmware/loader.o \
./Middlewares/trustedfirmware/security_cnt.o \
./Middlewares/trustedfirmware/uart_stdout.o 

C_DEPS += \
./Middlewares/trustedfirmware/bl2_main.d \
./Middlewares/trustedfirmware/boot_record.d \
./Middlewares/trustedfirmware/bootutil_misc.d \
./Middlewares/trustedfirmware/flash_map.d \
./Middlewares/trustedfirmware/image_rsa.d \
./Middlewares/trustedfirmware/image_validate.d \
./Middlewares/trustedfirmware/keys.d \
./Middlewares/trustedfirmware/loader.d \
./Middlewares/trustedfirmware/security_cnt.d \
./Middlewares/trustedfirmware/uart_stdout.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/trustedfirmware/bl2_main.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bl2_main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/bl2_main.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/boot_record.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/src/boot_record.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/boot_record.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/bootutil_misc.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/src/bootutil_misc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/bootutil_misc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/flash_map.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/flash_map.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/flash_map.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/image_rsa.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/src/image_rsa.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/image_rsa.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/image_validate.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/src/image_validate.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/image_validate.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/keys.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/keys.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/keys.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/loader.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/src/loader.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/loader.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/security_cnt.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/bl2/src/security_cnt.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/security_cnt.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/trustedfirmware/uart_stdout.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/trustedfirmware/platform/ext/common/uart_stdout.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/trustedfirmware/uart_stdout.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

