################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/asn1parse.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/bignum.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/ctr_drbg.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/debug.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/error.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/memory_buffer_alloc.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/platform.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/platform_util.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/rsa.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/rsa_internal.c \
C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/sha256.c 

OBJS += \
./Middlewares/mbedtls/asn1parse.o \
./Middlewares/mbedtls/bignum.o \
./Middlewares/mbedtls/ctr_drbg.o \
./Middlewares/mbedtls/debug.o \
./Middlewares/mbedtls/error.o \
./Middlewares/mbedtls/memory_buffer_alloc.o \
./Middlewares/mbedtls/platform.o \
./Middlewares/mbedtls/platform_util.o \
./Middlewares/mbedtls/rsa.o \
./Middlewares/mbedtls/rsa_internal.o \
./Middlewares/mbedtls/sha256.o 

C_DEPS += \
./Middlewares/mbedtls/asn1parse.d \
./Middlewares/mbedtls/bignum.d \
./Middlewares/mbedtls/ctr_drbg.d \
./Middlewares/mbedtls/debug.d \
./Middlewares/mbedtls/error.d \
./Middlewares/mbedtls/memory_buffer_alloc.d \
./Middlewares/mbedtls/platform.d \
./Middlewares/mbedtls/platform_util.d \
./Middlewares/mbedtls/rsa.d \
./Middlewares/mbedtls/rsa_internal.d \
./Middlewares/mbedtls/sha256.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/mbedtls/asn1parse.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/asn1parse.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/asn1parse.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/bignum.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/bignum.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/bignum.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/ctr_drbg.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/ctr_drbg.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/ctr_drbg.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/debug.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/debug.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/debug.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/error.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/error.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/error.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/memory_buffer_alloc.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/memory_buffer_alloc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/memory_buffer_alloc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/platform.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/platform.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/platform.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/platform_util.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/platform_util.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/platform_util.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/rsa.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/rsa.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/rsa.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/rsa_internal.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/rsa_internal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/rsa_internal.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/mbedtls/sha256.o: C:/Users/hanne/Documents/UNI/Sem1/Softwareprojekt/TF-M_ported_for_L552ZE-Q/Middlewares/Third_Party/mbedtls/library/sha256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -g3 -DTFM_DEV_MODE -DNDEBUG '-D__ARM_FEATURE_CMSE=3' -DSTM32L552xx -DUSE_HAL_DRIVER -DMCUBOOT_SIGN_RSA '-DMCUBOOT_SIGN_RSA_LEN=3072' -DMCUBOOT_VALIDATE_PRIMARY_SLOT -DBL2 -DMCUBOOT_OVERWRITE_ONLY -DMCUBOOT_USE_FLASH_AREA_GET_SECTORS '-DMCUBOOT_TARGET_CONFIG=<flash_layout.h>' '-DMBEDTLS_CONFIG_FILE=<config-boot.h>' '-DMCUBOOT_IMAGE_NUMBER=2' -D__thumb2__ -c -I../../Inc -I../../../../../Drivers/CMSIS/Include -I../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../../../Drivers/BSP/STM32L562E-DK -I../../../Linker -I../../../../../Middlewares/Third_Party/mbedtls/include -I../../../../../Middlewares/Third_Party/mbedtls/include/mbedtls -I../../../../../Middlewares/Third_Party/trustedfirmware -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/common -I../../../../../Middlewares/Third_Party/trustedfirmware/platform/ext/driver -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/include -I../../../../../Middlewares/Third_Party/trustedfirmware/bl2/ext/mcuboot/bootutil/include -Os -ffunction-sections -fdata-sections -Wall -fshort-enums -fshort-wchar -funsigned-char -mcmse -Wall -Wno-format -Wno-return-type -fstack-usage -MMD -MP -MF"Middlewares/mbedtls/sha256.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

